[package]
name = "rady"
version = "0.6.9"
edition = "2024"
rust-version = "1.85"
description = "Rady has moved to Koelu; install the koelu crate instead"
license = "MIT"
readme = "README.md"
repository = "https://github.com/keys-i/rady"
publish = ["crates-io"]

[[bin]]
name = "rady"
path = "src/main.rs"
